### ISSUE TITLE
Augmentation

### ISSUE THREAD

**Issue by unkn0wnxx** [wyharveychen/CloserLookFewShot#11]
Hi, I have a question regarding your augmentation methods. In your code, scaling and center crop is still applied when augmentation is False in both training and validation stage. In the repo jakesnell/prototypical-networks, only scaling is applied. Is this intended? If it is, any specific reason?

**Comment by wyharveychen** [comment]
Hello, I follow the center crop strategy as in 
https://github.com/facebookresearch/low-shot-shrink-hallucinate
I remember that it would slightly increase the accuracy by getting rid of the margin (not sure).
