### ISSUE TITLE
Extend your work for my thesis?

### ISSUE THREAD

**Issue by jonkoi** [wyharveychen/CloserLookFewShot#16]
Hi,

Firstly, I'd like to say that I really like your paper. You've some excellent work.

My situation is that I got my master thesis whose goal is to implement and comparatively evaluate few-shot learning methods but then your paper arrived. I have not started my thesis yet, but for specifc reasons, the topic might be hard to change.

I am still discussing with my supervisor but It is possible that I will extend your project. Thus, I would like to ask if you are still continuing this work. I will look for a different direction if you are.

Thank you.

**Comment by wyharveychen** [comment]
Hello, I currently have no plan on continuing this work. Feel free to get deep into a new direction!
