### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by EmmanouelP** [wyharveychen/CloserLookFewShot#28]
I used the below command to try running the code:
python ./train.py --dataset miniImagenet --model Conv4 --method baseline --train_aug

but I run into the error:
Traceback (most recent call last):
  File "./train.py", line 100, in <module>
    base_datamgr    = SimpleDataManager(image_size, batch_size = 16)
  File "/media/data2/manolis/CloserLookFewShot/data/datamgr.py", line 53, in __init__
    super(SimpleDataManager, self).__init__()
TypeError: super() argument 1 must be type, not classobj

Any insight on that?? Thanks in advance.

**Comment by wyharveychen** [comment]
Hello, can you double check whether you are using python3? Thanks!

**Comment by EmmanouelP** [comment]
Absolutely my bad....thanks for pointing out.
