### ISSUE TITLE
can you release the miniImageNet directly? the ILSVRC is too large...

### ISSUE THREAD

**Issue by bengepai** [wyharveychen/CloserLookFewShot#29]
thanks~

**Comment by dangpzanco** [comment]
See [https://github.com/oscarknagg/few-shot](https://github.com/oscarknagg/few-shot) for a `miniImageNet` download link

**Comment by bengepai** [comment]
thank you

**Comment by banjuanshua** [comment]
Can you use this miniImageNet download link get reported result?
