### ISSUE TITLE
Can I use the miniImagenet from here?

### ISSUE THREAD

**Issue by Franklin-Yao** [wyharveychen/CloserLookFewShot#45]
Can I use the miniImagenet from 
https://drive.google.com/file/d/1fJAK5WZTjerW7EWHHQAR9pRJVNg1T1Y7/view?usp=sharing
It's used in MetaOptnet. https://github.com/kjunelee/MetaOptNet. And it's much smaller.

**Comment by ShnDanYao** [comment]
I successfully use the miniImagenet  which is just about 3GB, but you must modify the "write_miniImagenet_filelist.py" and the "write_miniImagenet_filelist.py".

**Comment by Franklin-Yao** [comment]
I have done that. Your reply is 

> I successfully use the miniImagenet which is just about 3GB, but you must modify the "write_miniImagenet_filelist.py" and the "write_miniImagenet_filelist.py".

I have done that. If your reply is earlier, that will be more helpful.

**Comment by lerndeep** [comment]
could you share the changed file? I also want to use just a 3GB file but I have no idea what I need to change from "write_minilmagenet_filelist.py" and write_miniImagenet_filelist.py".

**Comment by johnnyasd12** [comment]
If you want to download mini-Imagenet and modify the code manually, maybe [this (for code modification)](https://github.com/wyharveychen/CloserLookFewShot/issues/37#issuecomment-524598549) and [this (for downloading dataset)](https://github.com/wyharveychen/CloserLookFewShot/issues/29#issuecomment-506476939) might help?
