### ISSUE TITLE
How to run domain adaptation test?

### ISSUE THREAD

**Issue by janetwise** [wyharveychen/CloserLookFewShot#57]
Hello, 

This code base is amazing to learn few-shot learning! I was able to follow the train/save_feature/test for the baseline and meta algorithms separately and obtained similar results as the paper. I'd like to try the domain adaptation on these methods too. How should I do it to see adaptation from miniImagenet to CUB? What's the command line to do it? For example,
1. python ./train.py --dataset miniImagenet --model Conv4 --method baseline --train_aug
2. python ./save_feature.py --dataset miniImagenet --model Conv4 --method baseline --train_aug
3. python ./test.py --dataset CUB --model Conv4 --method baseline --train_aug --adaptation

Is #3 correct to use to call baseline finetune on new domain CUB data from the trained embedding using miniImagenet?? How do I specify it (call miniImagenet trained embedding) from the command line?

Thank you very much in advance!!

**Comment by johnnyasd12** [comment]
The following should work:

`python ./train.py --dataset cross --model Conv4 --method baseline --train_aug`

`python ./save_feature.py --dataset cross --model Conv4 --method baseline --train_aug`

`python ./test.py --dataset cross --model Conv4 --method baseline --train_aug`

You could check `io_utils.py` and `train.py` for more detail.

**Comment by janetwise** [comment]
@johnnyasd12 Thank you so much for the hint! Looking at the code, dataset cross does look like the right command line parameter to go for domain adaptation test.
