### ISSUE TITLE
Clarify # of epochs

### ISSUE THREAD

**Issue by jayelm** [wyharveychen/CloserLookFewShot#6]
Hi, thanks for releasing code!

Just to clarify, in the paper you train "60,000 episodes for 1-shot tasks" - say I'm running ProtoNets on the CUB dataset - by default each epoch consists of 100 sampled episodes, correct? So the results in the paper are reported with the best model (according to val) after 600 epochs?

**Comment by wyharveychen** [comment]
Yes!

**Comment by jayelm** [comment]
Thanks!
