### ISSUE TITLE
assert params.num_classes >= 1597, 'class number need to be larger than max label id in base class'

### ISSUE THREAD

**Issue by wenbohuang1002** [wyharveychen/CloserLookFewShot#70]
I have processed the omniglot into noLatin.json as the requirement, however, it raises this issue.

Traceback (most recent call last):
  File "train.py", line 108, in <module>
    assert params.num_classes >= 1597, 'class number need to be larger than max label id in base class'
AssertionError: class number need to be larger than max label id in base class

The form of Json is 
"{label_names": ["Alphabet_of_the_Magi/character01","Alphabet_of_the_Magi/character02",..."ULOG/character26"],"image_names": ["E:/Project/CloserLookFewShot-master/filelists/omniglot/images/Alphabet_of_the_Magi/character01/0709_19.png",...,"E:/Project/CloserLookFewShot-master/filelists/omniglot/images/ULOG/character26/1623_15.png"],"image_labels": [0,...,1596]}

**Comment by llg123123** [comment]
> 

I also encountered the same problem in the training of the cross_char . How did you solve it. Thank you very much!

**Comment by kevin-xiaoxin** [comment]
> I have processed the omniglot into noLatin.json as the requirement, however, it raises this issue.
> 
> Traceback (most recent call last): File "train.py", line 108, in assert params.num_classes >= 1597, 'class number need to be larger than max label id in base class' AssertionError: class number need to be larger than max label id in base class
> 
> The form of Json is "{label_names": ["Alphabet_of_the_Magi/character01","Alphabet_of_the_Magi/character02",..."ULOG/character26"],"image_names": ["E:/Project/CloserLookFewShot-master/filelists/omniglot/images/Alphabet_of_the_Magi/character01/0709_19.png",...,"E:/Project/CloserLookFewShot-master/filelists/omniglot/images/ULOG/character26/1623_15.png"],"image_labels": [0,...,1596]}


When you train the model, you  need to specify num_classes, for example  python ./train.py --model Conv4 --method baseline --num_classes 1597

**Comment by wenbohuang1002** [comment]
> > I have processed the omniglot into noLatin.json as the requirement, however, it raises this issue.
> > Traceback (most recent call last): File "train.py", line 108, in assert params.num_classes >= 1597, 'class number need to be larger than max label id in base class' AssertionError: class number need to be larger than max label id in base class
> > The form of Json is "{label_names": ["Alphabet_of_the_Magi/character01","Alphabet_of_the_Magi/character02",..."ULOG/character26"],"image_names": ["E:/Project/CloserLookFewShot-master/filelists/omniglot/images/Alphabet_of_the_Magi/character01/0709_19.png",...,"E:/Project/CloserLookFewShot-master/filelists/omniglot/images/ULOG/character26/1623_15.png"],"image_labels": [0,...,1596]}
> 
> When you train the model, you need to specify num_classes, for example python ./train.py --model Conv4 --method baseline --num_classes 1597

Thank you for the helpful answer, however, I have added the --num_classes 1597 or defined the num_classes = 1597 before reporting this issue. I think there may have another reason.

**Comment by wenbohuang1002** [comment]
> 
Thank you for the helpful answer, however, I have added the --num_classes 1597 or defined the unm_classes = 1597 before reporting this issue. I think there may have another reason.


> > I have processed the omniglot into noLatin.json as the requirement, however, it raises this issue.
> > Traceback (most recent call last): File "train.py", line 108, in assert params.num_classes >= 1597, 'class number need to be larger than max label id in base class' AssertionError: class number need to be larger than max label id in base class
> > The form of Json is "{label_names": ["Alphabet_of_the_Magi/character01","Alphabet_of_the_Magi/character02",..."ULOG/character26"],"image_names": ["E:/Project/CloserLookFewShot-master/filelists/omniglot/images/Alphabet_of_the_Magi/character01/0709_19.png",...,"E:/Project/CloserLookFewShot-master/filelists/omniglot/images/ULOG/character26/1623_15.png"],"image_labels": [0,...,1596]}
> 
> When you train the model, you need to specify num_classes, for example python ./train.py --model Conv4 --method baseline --num_classes 1597

**Comment by kevin-xiaoxin** [comment]
> Thank you for the helpful answer, however, I have added the --num_classes 1597 or defined the unm_classes = 1597 before reporting this issue. I think there may have another reason.

Have you ever tried the cross domain tasks(miniImagenet-CUB) in table 3? I have met the problem of lower accuracy 52% in baseline using ResNet18. And I didn't get the reason of this. If you have done this research, can you tell me what the problem is? Thank you very much!

**Comment by wenbohuang1002** [comment]
> > Thank you for the helpful answer, however, I have added the --num_classes 1597 or defined the unm_classes = 1597 before reporting this issue. I think there may have another reason.
> 
> Have you ever tried the cross domain tasks(miniImagenet-CUB) in table 3? I have met the problem of lower accuracy 52% in baseline using ResNet18. And I didn't get the reason of this. If you have done this research, can you tell me what the problem is? Thank you very much!

Sorry, I do not have the imagenent dataset on my PC. Therefore, I tried cross_char instead but it can not run.

**Comment by yyou22** [comment]
Hello, were you able to resolve the issue of running cross_char? We were able to run cross_char with `python ./train.py --dataset cross_char --method baseline++  --num_classes 1597`, however the baseline++ accuracy (80%) is lower than baseline (85%) for omniglot -> EMNIST. Please let us know if you also have this issue, thank you so much.
